//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRetail.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public System.DateTime last_updated { get; set; }
        public decimal price { get; set; }    
    }
}
